### ISSUE TITLE
greycite API down?

### ISSUE THREAD

**Issue by sherbrich** [cboettig/knitcitations#83] opened 2015-08-29 22:00 UTC
Over the past few days, my .bib files continue to be generated and documents compile, however, I get the following warnings:

Output created: TL1_grant_v4.pdf
Warning messages:
1: In greycite(x) : cannot reach Greycite API
2: In greycite(x) : cannot reach Greycite API
3: In greycite(x) : cannot reach Greycite API

And all of my citations are listed as "unknown". It appears the Greycite page is down? Does this mean I cannot use knitcitations?

**Comment by cboettig** [comment] 2015-08-30 20:33
Thanks for the bug report.  It does seem like Greycite is down, perhaps @phillord can look into that?

Note that in knitcitations, greycite is only being used for URLs; you shouldn't see this error if you are just providing DOI strings.  (If you are, paste a minimal example that reproduces the error you see and I can look into it).

**Comment by sherbrich** [comment] 2015-09-01 02:14
The DOI strings still work, thanks!

**Comment by phillord** [comment] 2015-09-01 07:24
We've been having some disk problems recently, which is probably the cause of this. Will look at this as soon as we can.

**Comment by phillord** [comment] 2015-09-01 11:25
Should be fixed now.

**Closed** 2015-10-02 04:34 UTC
